default: &default
  adapter: postgres
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: business_ride_dev
  pool: 5
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: business_ride_test
  pool: 5
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: business_ride_prod
  pool: 5
  password: root
